# Generated by Django 4.0.2 on 2022-02-25 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=200, unique=True)),
                ('total_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('city', models.CharField(max_length=20)),
                ('shop_site', models.CharField(max_length=50, null=True)),
                ('number_line_item', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrderAPIView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId1', models.CharField(max_length=200)),
                ('total_price1', models.FloatField(blank=True, default=0.0, null=True)),
                ('orderName1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Line_Item_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item_order_id', models.CharField(max_length=20, unique=True)),
                ('shop_site', models.CharField(max_length=50, null=True)),
                ('fulfillment_status', models.CharField(max_length=50)),
                ('image_src', models.URLField(max_length=255)),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('price', models.FloatField(default=0.0, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('sku', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=100)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
