# Generated by Django 4.0.2 on 2022-02-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_item_order',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
