# Generated by Django 4.0.2 on 2022-02-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_line_item_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line_item_order',
            name='line_item_order_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
